#this code is a soul talking to Aditya
print('loading.......\tS\tO\tu\tL')
print('::it almost done::')
print("\n___________DEVIL IS HERE__________\n")
print(">hloo""\nhooooo aaaaaa"+" iam your soul\n")
print("adi:> aaaaaaaaaaaAAAAaa")
print("soul:> Silence")
print("soul:> say hii")
print("adi:> haaaai")
print("adi:> OMG OMG OMG" + " from where you came sir?!!!")
location = input("adi:> enter your location soul :: ")
print("adi:> ok ok so you came from "+location)
print("adi:> may i ask you your name sir")
#asking to input name of soul
name=input("adi:> enter your name soul :: ")
print("adi:> hii "+name)
print("soul:> idiot i will now kill you.respect!!!")
print("adi:> OH No NO No sorry sir")
print("soul:> ok")
print("soul:> whats time now?")
print("adi:> its toooo late")
print("soul:> Time!!!!!!!!!!")
#as asking adi to input current Time
time = int(input("enter time adi :: "))
print("soul:> "+str(time)+"is ok for me")
print("adi:> jai hanumman gayan gun sagar..........")
print("soul:> oh no wait are you chanting HANUMMAN CHALISAA")
print("soul:> aaaaaaaaaaaaaaaa iam going")
print("    \      /")
print("    - puff -")
print("    .       .")
print("   .         .")
print("  .           .")
print(" .             .")
print(".               .")
